In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [5]:
x2 = np.array([[2,3],[5,6]])
print(x2)

[[2 3]
 [5 6]]


In [6]:
print(x.shape)
print(x2.shape)
print(x.ndim)
print(x2.ndim)

(4,)
(2, 2)
1
2


In [7]:
a = np.arange(-5,6,.5)
print(a)
print(a.size)       # gives number of elements
print(a.shape)      # finds rows and columns

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5  5.   5.5]
22
(22,)


In [8]:
b = np.linspace(1,10,50)        # total no. of elements=50 , linear spacing
print(b)


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [9]:
c = np.random.random((3,3))     #(3,3) is size of matrix
print(c)

[[0.08647046 0.69209787 0.74541771]
 [0.98113154 0.83863029 0.06871539]
 [0.29315535 0.2364139  0.22725415]]


In [10]:
d = np.random.random((5,5))     
print(d)

[[0.82417726 0.86023104 0.56232924 0.76573896 0.6955541 ]
 [0.83940548 0.07651256 0.82779505 0.44310056 0.37757123]
 [0.5400949  0.60594145 0.13536471 0.84666817 0.64005649]
 [0.40700568 0.66890317 0.20883165 0.16740069 0.63450643]
 [0.89091677 0.69797165 0.32881378 0.20295235 0.1543314 ]]


In [11]:
e = np.random.randn(3,3)    # natural numbers
print(e)
print(e.shape)
print(e.size)

[[-0.87719337  0.9757207   0.96884007]
 [ 0.72068318 -0.92627005 -1.58343575]
 [ 0.0815038   1.45829292 -0.4946521 ]]
(3, 3)
9


In [12]:
f = np.random.randint(1,10,(3,3,3))
print(f)
print(f.shape)
print(f.size)

[[[3 5 7]
  [3 2 2]
  [4 5 3]]

 [[3 2 8]
  [1 2 9]
  [9 4 8]]

 [[1 4 5]
  [3 4 5]
  [3 9 3]]]
(3, 3, 3)
27


In [13]:
g = np.linspace(1,100,90)
print(g)
print(g.shape)

[  1.           2.11235955   3.2247191    4.33707865   5.4494382
   6.56179775   7.6741573    8.78651685   9.8988764   11.01123596
  12.12359551  13.23595506  14.34831461  15.46067416  16.57303371
  17.68539326  18.79775281  19.91011236  21.02247191  22.13483146
  23.24719101  24.35955056  25.47191011  26.58426966  27.69662921
  28.80898876  29.92134831  31.03370787  32.14606742  33.25842697
  34.37078652  35.48314607  36.59550562  37.70786517  38.82022472
  39.93258427  41.04494382  42.15730337  43.26966292  44.38202247
  45.49438202  46.60674157  47.71910112  48.83146067  49.94382022
  51.05617978  52.16853933  53.28089888  54.39325843  55.50561798
  56.61797753  57.73033708  58.84269663  59.95505618  61.06741573
  62.17977528  63.29213483  64.40449438  65.51685393  66.62921348
  67.74157303  68.85393258  69.96629213  71.07865169  72.19101124
  73.30337079  74.41573034  75.52808989  76.64044944  77.75280899
  78.86516854  79.97752809  81.08988764  82.20224719  83.31460674
  84.426966

In [14]:
g2 = g.reshape(45,2)        # or (15,3,2) or (30,3)
print(g2)
g3 = g.reshape(30,3)        # or (15,3,2) or (30,3)
print(g3)

[[  1.           2.11235955]
 [  3.2247191    4.33707865]
 [  5.4494382    6.56179775]
 [  7.6741573    8.78651685]
 [  9.8988764   11.01123596]
 [ 12.12359551  13.23595506]
 [ 14.34831461  15.46067416]
 [ 16.57303371  17.68539326]
 [ 18.79775281  19.91011236]
 [ 21.02247191  22.13483146]
 [ 23.24719101  24.35955056]
 [ 25.47191011  26.58426966]
 [ 27.69662921  28.80898876]
 [ 29.92134831  31.03370787]
 [ 32.14606742  33.25842697]
 [ 34.37078652  35.48314607]
 [ 36.59550562  37.70786517]
 [ 38.82022472  39.93258427]
 [ 41.04494382  42.15730337]
 [ 43.26966292  44.38202247]
 [ 45.49438202  46.60674157]
 [ 47.71910112  48.83146067]
 [ 49.94382022  51.05617978]
 [ 52.16853933  53.28089888]
 [ 54.39325843  55.50561798]
 [ 56.61797753  57.73033708]
 [ 58.84269663  59.95505618]
 [ 61.06741573  62.17977528]
 [ 63.29213483  64.40449438]
 [ 65.51685393  66.62921348]
 [ 67.74157303  68.85393258]
 [ 69.96629213  71.07865169]
 [ 72.19101124  73.30337079]
 [ 74.41573034  75.52808989]
 [ 76.64044944

In [15]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print()
print(y)

[[4 5 1]
 [1 5 7]
 [6 9 9]]

[[1 1 9]
 [2 9 7]
 [2 7 3]]


In [16]:
print(x-y)      # element wise subtraction
print(x*y)      # element wise multiplication
print(x/y)      # element wise division
print(x//y)     # element wise floor division
print(x%y)      # element wise modulus
print(x**y)     # element wise exponentiation


[[ 3  4 -8]
 [-1 -4  0]
 [ 4  2  6]]
[[ 4  5  9]
 [ 2 45 49]
 [12 63 27]]
[[4.         5.         0.11111111]
 [0.5        0.55555556 1.        ]
 [3.         1.28571429 3.        ]]
[[4 5 0]
 [0 0 1]
 [3 1 3]]
[[0 0 1]
 [1 5 0]
 [0 2 0]]
[[      4       5       1]
 [      1 1953125  823543]
 [     36 4782969     729]]


In [17]:
# dot product
print(np.dot(x,y))      # dot product
print(x.dot(y))         # same dot product
print(np.cross(x,y))    # cross product
print(np.matmul(x,y))   # atrix multiplication

[[ 16  56  74]
 [ 25  95  65]
 [ 42 150 144]]
[[ 16  56  74]
 [ 25  95  65]
 [ 42 150 144]]
[[ 44 -35  -1]
 [-28   7  -1]
 [-36   0  24]]
[[ 16  56  74]
 [ 25  95  65]
 [ 42 150 144]]


In [18]:
print(x.sum())      # sum of all elements
print(x.sum(axis=0))    #sum of each coloumn
print(x.sum(axis=1))    #sum of each row
print(x.mean())     #mean of all elements
print(x.mean(axis=0))   #mean of each column
print(x.mean(axis=1))   #mean of each row
print(x.std())  #standard deviation of all elements
print(x.std(axis=0))    #standard deviation of each coloumn
print(x.std(axis=1))    #standard deviation of each row
print(np.median(x))     #median of all elements
print(np.median(x,axis=0))      #median of each column
print(np.median(x,axis=1))      #median of each row

47
[11 19 17]
[10 13 24]
5.222222222222222
[3.66666667 6.33333333 5.66666667]
[3.33333333 4.33333333 8.        ]
2.779999111821512
[2.05480467 1.88561808 3.39934634]
[1.69967317 2.49443826 1.41421356]
5.0
[4. 5. 7.]
[4. 5. 9.]


In [19]:
import matplotlib.pyplot as plt



In [20]:
t = np.linspace(0,4*np.pi,100)
y=np.sin(t)
x=np.cos(t)
plt.plot(t,y)
plt.plot(t,x,'bo')
plt.show()

In [21]:
np.sin(3)

0.1411200080598672

In [22]:
rainfall=[20,30,40,50,60,70,80,90,100,110,120,130]
months=['Jan','Feb','Mar','Apr','May','June','July','Aug','Sep','Oct','Nov','Dec']
plt.bar(months,rainfall)

<BarContainer object of 12 artists>

In [23]:
# boolean filtering
data=np.random.randint(1,1000,(5,5))
data


array([[893, 563,  28, 137, 420],
       [644, 639, 372, 261, 675],
       [612, 494, 645, 613, 112],
       [332,   7,  75, 444, 630],
       [482, 999, 547, 397, 278]])

In [27]:
#noob way for getting the filtered data
for i in data:
    for j in i:
        if j<500:
            print(j,end=' ')
    

28 137 420 372 261 494 112 332 7 75 444 482 397 278 

In [28]:
# pythonic way
data < 500 # boolean array

array([[False, False,  True,  True,  True],
       [False, False,  True,  True, False],
       [False,  True, False, False,  True],
       [ True,  True,  True,  True, False],
       [ True, False, False,  True,  True]])

In [29]:
data[data<500]

array([ 28, 137, 420, 372, 261, 494, 112, 332,   7,  75, 444, 482, 397,
       278])

In [31]:
data[(data<100)|(data>500)]

array([893, 563,  28, 644, 639, 675, 612, 645, 613,   7,  75, 630, 999,
       547])

In [32]:
data

array([[893, 563,  28, 137, 420],
       [644, 639, 372, 261, 675],
       [612, 494, 645, 613, 112],
       [332,   7,  75, 444, 630],
       [482, 999, 547, 397, 278]])

In [35]:
data1=np.random.randint(1,1000,(8,8))
data1

array([[347,  58, 276, 802, 316, 384, 705, 659],
       [992, 740, 779, 254, 327, 787, 154, 175],
       [348,  14, 306, 813, 441,  62, 914, 800],
       [ 50,  85, 870, 671, 749,  19, 602, 740],
       [148, 903, 915, 505, 490,  97, 899,  15],
       [179, 537, 598, 507, 734, 538, 746, 906],
       [904,  75, 162, 373, 338, 555, 456, 798],
       [904,  57, 592, 747, 713, 459, 476,  46]])

In [41]:
#slicing
sli=data1[:5,:5]
print(sli)

[[347  58 276 802 316]
 [992 740 779 254 327]
 [348  14 306 813 441]
 [ 50  85 870 671 749]
 [148 903 915 505 490]]


In [42]:
data1[:,[3,6,7]]

array([[802, 705, 659],
       [254, 154, 175],
       [813, 914, 800],
       [671, 602, 740],
       [505, 899,  15],
       [507, 746, 906],
       [373, 456, 798],
       [747, 476,  46]])

In [45]:
data1[2::-2,2:-2]

array([[306, 813, 441,  62],
       [276, 802, 316, 384]])

In [47]:
data1[:,:-1]

array([[347,  58, 276, 802, 316, 384, 705],
       [992, 740, 779, 254, 327, 787, 154],
       [348,  14, 306, 813, 441,  62, 914],
       [ 50,  85, 870, 671, 749,  19, 602],
       [148, 903, 915, 505, 490,  97, 899],
       [179, 537, 598, 507, 734, 538, 746],
       [904,  75, 162, 373, 338, 555, 456],
       [904,  57, 592, 747, 713, 459, 476]])